### ISSUE TITLE
predict_disorder_batch NOT correct invalid amino acid

### ISSUE THREAD

**Issue by zyh4482** [idptools/metapredict#15]
Hello! 
Thanks for your latest metapredict tool. 

I'm working on python command of metapredict. 

When I call the function `predict_disorder_batch(fasta_dict, return_domains = False, show_progress_bar = True)` to create scores for each AA, I got these error messages: 

```
Traceback (most recent call last):
  File "/home/zyh/software/miniforge3/lib/python3.10/site-packages/metapredict/backend/encode_sequence.py", line 53, in one_hot
    m[i, ONE_HOT[seq[i]]] = 1
KeyError: 'U'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zyh/project/IDR/script/utils/run_metapredict.py", line 40, in <module>
    predict_disorder(args.input, args.output)
  File "/home/zyh/project/IDR/script/utils/run_metapredict.py", line 27, in predict_disorder
    meta_dict_score = meta.predict_disorder_batch(fasta_dict, return_domains = False, show_progress_bar = True)
  File "/home/zyh/software/miniforge3/lib/python3.10/site-packages/metapredict/meta.py", line 625, in predict_disorder_batch
    return _batch_predict(input_sequences,
  File "/home/zyh/software/miniforge3/lib/python3.10/site-packages/metapredict/backend/batch_predict.py", line 446, in batch_predict
    seqs_padded = pad_sequence([encode_sequence.one_hot(seq).float() for seq in batch], batch_first=True)
  File "/home/zyh/software/miniforge3/lib/python3.10/site-packages/metapredict/backend/batch_predict.py", line 446, in <listcomp>
    seqs_padded = pad_sequence([encode_sequence.one_hot(seq).float() for seq in batch], batch_first=True)
  File "/home/zyh/software/miniforge3/lib/python3.10/site-packages/metapredict/backend/encode_sequence.py", line 56, in one_hot
    raise ValueError(error_str)
ValueError: Invalid amino acid detected: U
```

I see the correction held in `predict_disorder_fasta` using `protfasta` module. `predict_disorder_batch` and `predict_disorder` both do not check the sequence validity. I was wondering if I need to convert the sequence prior to `predict_disorder_batch` or `predict_disorder`. If so, how should I do this ?

**Comment by alexholehouse** [comment]
Yeah - your best bet is to read the FASTA file in with [protfasta.read_fasta](https://protfasta.readthedocs.io/en/latest/read_fasta.html) and set the `invalid_sequence_action` to `'convert'` which will – where possible – convert residues to valid sequences. Alternatively, you could set it to `remove` in which case any sequences with non-standard amino acid residues will be discarded.

**Comment by zyh4482** [comment]
Thank you very much!
